### ISSUE TITLE
Flight Restrictions Answers

### ISSUE THREAD

**Issue by BPlanterose** [bixiou/oecd_climate#1]
For Table 37, a lot of answers are PNR (26/62 fors 1000km, 24/67 for 3000km and 33/66 for 1trip/2years).

Should we change the wording of the questions? Do you think it's because those questions are at the end of the survey and people get weary?

@bixiou : you said we might remove the PNR option here, do you think it might lead people to answer randomly here?

**Comment by bixiou** [comment]
Yes, that's why I suggested removing the PNR option for this question. Note that many people may answer PNR because they genuinely don't know or like neither options, so it's quite understandable here.

**Comment by bixiou** [comment]
I removed PNR option.

**Comment by bixiou** [comment]
I changed the 2000 miles per year option to 600 miles (as the other) but at the global level instead of the US level.
Comparing US vs. global allows to better test the underlying model of relative utility than 600 vs. 2000 miles. 
The new prediction is that the "poor" (Americans who fly less than the US average) will favor tradable quotas more in the US version than in the global one (because they receive more in dividends), while the "rich" (those flying more than average) will favor rationing more in the US than in the global.
